branches: gh-pages
pipeline:
    deploy:
        image: ghcr.io/williamjacksn/netlify-cli
        environment:
          - HOME=/home/node
        secrets: [ netlify_site_id, netlify_auth_token ]
        commands:
          - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod