pipeline:
    deploy:
      image: ghcr.io/williamjacksn/netlify-cli
      secrets: [ netlify_site_id, netlify_auth_token ]
      commands:
        - HOME=/home/node netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod

branches: gh-pages
