title: "Catvibers Blog"
tagline: "Welcome to the Catvibers Blog!"
description: "Revamped Catvibers Blog, W.I.P."
github_username: Catvibers
baseurl: "/"
url: "https://catvibers.github.io"

plugins:
  - jekyll-remote-theme
  - jemoji

remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md

font-size: small