title: "Catvibers Blog"
tagline: "Welcome to the Catvibers Blog!"
description: "Revamped Catvibers Blog, W.I.P."
github_username: Catvibers
baseurl: "/Website"
url: "https://catvibers.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

font-size: small
theme: jekyll-theme-hacker