source "https://rubygems.org"

gem "jekyll-shell-theme"
gem "kramdown", ">= 2.3.0"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
    gem 'jekyll-remote-theme'
    gem 'jemoji'
end
